//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using mvc.Models;
using System;
namespace mvc.Models.Sys
{
	public class Virtual_SysSampleModel
    {
		 public string Id { get; set; }
        public string Name { get; set; }
        public int? Age { get; set; }
        public DateTime? Bir { get; set; }
        public string Photo { get; set; }
        public string Note { get; set; }
        public DateTime? CreateTime { get; set; }
         
    }
}
