//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using mvc.Models;
using System;
namespace mvc.Models.Sys
{
	public class Virtual_SysModuleModel
    {
		 public string Id { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string ParentId { get; set; }
        public string Url { get; set; }
        public string Iconic { get; set; }
        public int? Sort { get; set; }
        public string Remark { get; set; }
        public bool Enable { get; set; }
        public string CreatePerson { get; set; }
        public DateTime? CreateTime { get; set; }
        public bool IsLast { get; set; }
        public byte[] Version { get; set; }
         
    }
}
