//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using mvc.Models;
using mvc.Common;
using Microsoft.Practices.Unity;
using mvc.IBLL;
using mvc.IDAL;
using mvc.BLL.Core;
using mvc.Models.Sys;
namespace mvc.BLL
{
    public partial class SysModuleBLL: Virtual_SysModuleBLL,ISysModuleBLL
    {
        

    }
}
