//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using mvc.Models;
using mvc.Common;
using Microsoft.Practices.Unity;
using mvc.IBLL;
using mvc.IDAL;
using mvc.BLL.Core;
using mvc.Models.Sys;
namespace mvc.BLL
{
    public class Virtual_JOBTestScoreBLL
    {
        [Dependency]
        public IJOBTestScoreRepository m_Rep { get; set; }

        public virtual List<JOBTestScoreModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<JOBTestScore> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
                                
                                a=>a.Name.Contains(queryStr)
                                || a.StudentId.Contains(queryStr)
                                
                                );
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<JOBTestScoreModel> CreateModelList(ref IQueryable<JOBTestScore> queryData)
        {

            List<JOBTestScoreModel> modelList = (from r in queryData
                                              select new JOBTestScoreModel
                                              {
                                                    Id = r.Id,
                                                    Name = r.Name,
                                                    StudentId = r.StudentId,
                                                    Score = r.Score,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, JOBTestScoreModel model)
        {
            try
            {
                JOBTestScore entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Suggestion.PrimaryRepeat);
                    return false;
                }
                entity = new JOBTestScore();
                               entity.Id = model.Id;
                entity.Name = model.Name;
                entity.StudentId = model.StudentId;
                entity.Score = model.Score;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Suggestion.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
					if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        
       

        public virtual bool Edit(ref ValidationErrors errors, JOBTestScoreModel model)
        {
            try
            {
                JOBTestScore entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Suggestion.Disable);
                    return false;
                }
                                              entity.Id = model.Id;
                entity.Name = model.Name;
                entity.StudentId = model.StudentId;
                entity.Score = model.Score;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Suggestion.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual JOBTestScoreModel GetById(string id)
        {
            if (IsExists(id))
            {
                JOBTestScore entity = m_Rep.GetById(id);
                JOBTestScoreModel model = new JOBTestScoreModel();
                                              model.Id = entity.Id;
                model.Name = entity.Name;
                model.StudentId = entity.StudentId;
                model.Score = entity.Score;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
          public void Dispose()
        { 
            
        }

    }
}
